eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
feign:
  hystrix:
    enabled: false
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000
logging:
  level:
    io:
      seata: info
mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: io.seata.sample.entity
server:
  port: 8180
spring:
  application:
    name: order-server
  cloud:
    alibaba:
      seata:
        tx-service-group: jxb_tx_group
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://XXX:3306/seat-order?useUnicode=true&characterEncoding=utf8&useSSL=true&useSSL=true&useAffectedRows=true
    username: 
    password: 